test

diff --git a/.github/workflows/deploy-changes.yaml b/.github/workflows/deploy-changes.yaml
--- a/.github/workflows/deploy-changes.yaml
+++ b/.github/workflows/deploy-changes.yaml
@@ -12,6 +12,17 @@ on:
           - prod
 
 jobs:
+  validate-input:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate environment input
+        run: |
+          if [[ ! "${{ github.event.inputs.environment }}" =~ ^(dev|demo|prod)$ ]]; then
+            echo "Error: Environment must be one of 'dev', 'demo', 'prod'"
+            exit 1
+          fi
+        shell: bash
+
   download_latest_draft_release_artifacts:
     runs-on: ubuntu-latest
     outputs:
@@ -25,7 +36,7 @@ jobs:
 
       - name: Download artifact from the latest draft release
         run: |
-          LATEST_DRAFT_URL=$(gh release list --draft --limit 1 | cut -f4)
+          LATEST_DRAFT_URL=$(gh release --limit 1 | cut -f4)
           gh release download --repo $GITHUB_REPOSITORY --name "files.zip" --dir "./" "$LATEST_DRAFT_URL"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
